steps:
  # 1. Docker 이미지 빌드
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/workflow-knue/apis-data-spcdeinfoservice:$SHORT_SHA"
      - "."

  # 2. 이미지 Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/workflow-knue/apis-data-spcdeinfoservice:$SHORT_SHA"

  # 3. Cloud Run 배포
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "apis-data-spcdeinfoservice"
      - "--image"
      - "gcr.io/workflow-knue/apis-data-spcdeinfoservice:$SHORT_SHA"
      - "--region"
      - "asia-northeast3"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--update-secrets"
      - "DATAGOKR_SERVICEKEY=DATAGOKR_SERVICEKEY:latest,AUTH_API_KEY=AUTH_API_KEY:latest"

images:
  - "gcr.io/workflow-knue/apis-data-spcdeinfoservice:$SHORT_SHA"
