apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apis-data-spcdeinfoservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: gcr.io/workflow-knue/apis-data-spcdeinfoservice
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
      containerConcurrency: 80
  traffic:
    - percent: 100
      latestRevision: true
